# Auto-generated metals database for coordination chemistry
# Contains METALS: list of dicts with symbol, smiles, atomic_weight, oxidation_states

METALS = [
    {'symbol': 'Sc', 'smiles': '[Sc]', 'atomic_weight': 44.956, 'oxidation_states': [3]},
    {'symbol': 'Ti', 'smiles': '[Ti]', 'atomic_weight': 47.867, 'oxidation_states': [2, 3, 4]},
    {'symbol': 'V', 'smiles': '[V]', 'atomic_weight': 50.942, 'oxidation_states': [2, 3, 4, 5]},
    {'symbol': 'Cr', 'smiles': '[Cr]', 'atomic_weight': 51.996, 'oxidation_states': [2, 3, 6]},
    {'symbol': 'Mn', 'smiles': '[Mn]', 'atomic_weight': 54.938, 'oxidation_states': [2, 4, 7]},
    {'symbol': 'Fe', 'smiles': '[Fe]', 'atomic_weight': 55.845, 'oxidation_states': [2, 3]},
    {'symbol': 'Co', 'smiles': '[Co]', 'atomic_weight': 58.933, 'oxidation_states': [2, 3]},
    {'symbol': 'Ni', 'smiles': '[Ni]', 'atomic_weight': 58.693, 'oxidation_states': [2, 3]},
    {'symbol': 'Cu', 'smiles': '[Cu]', 'atomic_weight': 63.546, 'oxidation_states': [1, 2]},
    {'symbol': 'Zn', 'smiles': '[Zn]', 'atomic_weight': 65.38, 'oxidation_states': [2]},
    {'symbol': 'Y', 'smiles': '[Y]', 'atomic_weight': 88.906, 'oxidation_states': [3]},
    {'symbol': 'Zr', 'smiles': '[Zr]', 'atomic_weight': 91.224, 'oxidation_states': [2, 3, 4]},
    {'symbol': 'Nb', 'smiles': '[Nb]', 'atomic_weight': 92.906, 'oxidation_states': [3, 5]},
    {'symbol': 'Mo', 'smiles': '[Mo]', 'atomic_weight': 95.95, 'oxidation_states': [2, 3, 4, 6]},
    {'symbol': 'Ru', 'smiles': '[Ru]', 'atomic_weight': 101.07, 'oxidation_states': [2, 3, 4, 6, 8]},
    {'symbol': 'Rh', 'smiles': '[Rh]', 'atomic_weight': 102.906, 'oxidation_states': [3]},
    {'symbol': 'Pd', 'smiles': '[Pd]', 'atomic_weight': 106.42, 'oxidation_states': [2, 4]},
    {'symbol': 'Ag', 'smiles': '[Ag]', 'atomic_weight': 107.868, 'oxidation_states': [1]},
    {'symbol': 'Cd', 'smiles': '[Cd]', 'atomic_weight': 112.414, 'oxidation_states': [2]},
    {'symbol': 'Hf', 'smiles': '[Hf]', 'atomic_weight': 178.49, 'oxidation_states': [4]},
    {'symbol': 'W', 'smiles': '[W]', 'atomic_weight': 183.84, 'oxidation_states': [2, 3, 4, 5, 6]},
    {'symbol': 'Re', 'smiles': '[Re]', 'atomic_weight': 186.207, 'oxidation_states': [4, 7]},
    {'symbol': 'Os', 'smiles': '[Os]', 'atomic_weight': 190.23, 'oxidation_states': [2, 3, 4, 6, 8]},
    {'symbol': 'Ir', 'smiles': '[Ir]', 'atomic_weight': 192.217, 'oxidation_states': [3, 4, 6]},
    {'symbol': 'Pt', 'smiles': '[Pt]', 'atomic_weight': 195.084, 'oxidation_states': [2, 4]},
    {'symbol': 'Au', 'smiles': '[Au]', 'atomic_weight': 196.967, 'oxidation_states': [1, 3]},
    {'symbol': 'Hg', 'smiles': '[Hg]', 'atomic_weight': 200.592, 'oxidation_states': [1, 2]},
    {'symbol': 'La', 'smiles': '[La]', 'atomic_weight': 138.905, 'oxidation_states': [3]},
    {'symbol': 'Ce', 'smiles': '[Ce]', 'atomic_weight': 140.116, 'oxidation_states': [3, 4]},
    {'symbol': 'Sm', 'smiles': '[Sm]', 'atomic_weight': 150.36, 'oxidation_states': [2, 3]},
    {'symbol': 'Eu', 'smiles': '[Eu]', 'atomic_weight': 151.964, 'oxidation_states': [2, 3]},
    {'symbol': 'Gd', 'smiles': '[Gd]', 'atomic_weight': 157.25, 'oxidation_states': [3]},
    {'symbol': 'Tb', 'smiles': '[Tb]', 'atomic_weight': 158.925, 'oxidation_states': [3, 4]},
    {'symbol': 'Dy', 'smiles': '[Dy]', 'atomic_weight': 162.5, 'oxidation_states': [3]},
    {'symbol': 'Er', 'smiles': '[Er]', 'atomic_weight': 167.259, 'oxidation_states': [3]},
    {'symbol': 'Yb', 'smiles': '[Yb]', 'atomic_weight': 173.045, 'oxidation_states': [2, 3]},
    {'symbol': 'Th', 'smiles': '[Th]', 'atomic_weight': 232.038, 'oxidation_states': [4]},
    {'symbol': 'U', 'smiles': '[U]', 'atomic_weight': 238.029, 'oxidation_states': [3, 4, 5, 6]},
]
