name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12
        channels: conda-forge
        auto-update-conda: true
        activate-environment: test-env
        environment-name: test-env

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y pytest matplotlib rdkit

    - name: Run tests
      shell: bash -l {0}
      run: |
        export PYTHONPATH=./src
        pytest
